export const CATEGORIES = {
  income: ['Maaş', 'Freelance', 'Yatırım', 'Diğer'],
  expense: ['Market', 'Kira', 'Faturalar', 'Eğlence', 'Ulaşım', 'Sağlık', 'Diğer']
};

export const COLORS = ['#0088FE', '#00C49F', '#FFBB28', '#FF8042', '#8884d8', '#82ca9d', '#ffc658'];

export const LANGUAGES = [
  { code: 'tr', name: 'Türkçe', flag: 'tr' },
  { code: 'en', name: 'English', flag: 'us' },
  { code: 'de', name: 'Deutsch', flag: 'de' },
  { code: 'es', name: 'Español', flag: 'es' },
  { code: 'fr', name: 'Français', flag: 'fr' },
  { code: 'ru', name: 'Русский', flag: 'ru' },
  { code: 'ja', name: '日本語', flag: 'jp' },
];

export const TRANSLATIONS = {
  tr: {
    title: 'Bütçe Takipçisi',
    subtitle: 'Finansal durumunuzu kolayca yönetin',
    netBalance: 'Net Bakiye',
    totalIncome: 'Toplam Gelir',
    totalExpense: 'Toplam Gider',
    budgetTarget: 'Bütçe Hedefi',
    used: 'Kullanıldı',
    addTransaction: 'Yeni İşlem Ekle',
    description: 'Açıklama',
    amount: 'Tutar',
    type: 'İşlem Türü',
    category: 'Kategori',
    date: 'Tarih',
    add: 'Ekle',
    recentTransactions: 'Son İşlemler',
    noTransactions: 'Henüz bir işlem eklenmedi.',
    income: 'Gelir',
    expense: 'Gider',
    pieChart: 'Pasta Grafiği',
    lineChart: 'Gelir/Gider Analizi',
    currencyRates: 'Döviz Kurları',
    currencyConverter: 'Döviz Dönüştürücü',
    quantity: 'Miktar',
    currency: 'Para Birimi',
    target: 'Hedef',
    result: 'Sonuç',
    exportPdf: 'Kaydet (PDF)',
    exportCsv: 'Excel/CSV',
    preparing: 'Hazırlanıyor...',
    graphicSummary: 'Grafik Özeti',
    budgetReport: 'Bütçe Raporu',
    creationDate: 'Oluşturulma Tarihi',
    period: 'Dönem',
    gold: 'Gram Altın',
    silver: 'Gram Gümüş',
    lastUpdate: 'Son güncelleme',
    monthlyLimit: 'Aylık Bütçe Limiti'
  },
  en: {
    title: 'Budget Tracker',
    subtitle: 'Manage your finances easily',
    netBalance: 'Net Balance',
    totalIncome: 'Total Income',
    totalExpense: 'Total Expense',
    budgetTarget: 'Budget Target',
    used: 'Used',
    addTransaction: 'Add New Transaction',
    description: 'Description',
    amount: 'Amount',
    type: 'Transaction Type',
    category: 'Category',
    date: 'Date',
    add: 'Add',
    recentTransactions: 'Recent Transactions',
    noTransactions: 'No transactions added yet.',
    income: 'Income',
    expense: 'Expense',
    pieChart: 'Pie Chart',
    lineChart: 'Income/Expense Analysis',
    currencyRates: 'Exchange Rates',
    currencyConverter: 'Currency Converter',
    quantity: 'Quantity',
    currency: 'Currency',
    target: 'Target',
    result: 'Result',
    exportPdf: 'Save (PDF)',
    exportCsv: 'Excel/CSV',
    preparing: 'Preparing...',
    graphicSummary: 'Graphic Summary',
    budgetReport: 'Budget Report',
    creationDate: 'Creation Date',
    period: 'Period',
    gold: 'Gram Gold',
    silver: 'Gram Silver',
    lastUpdate: 'Last update',
    monthlyLimit: 'Monthly Budget Limit'
  },
  // Diğer diller için varsayılan olarak İngilizce veya basit çeviriler kullanılabilir.
  // Yer tasarrufu için burada sadece TR ve EN detaylı verildi, diğerleri EN kopyası olabilir veya genişletilebilir.
  de: { title: 'Budget-Tracker', subtitle: 'Verwalten Sie Ihre Finanzen einfach', netBalance: 'Nettosaldo', totalIncome: 'Gesamteinkommen', totalExpense: 'Gesamtausgaben', budgetTarget: 'Budgetziel', used: 'Verwendet', addTransaction: 'Neue Transaktion', description: 'Beschreibung', amount: 'Betrag', type: 'Transaktionstyp', category: 'Kategorie', date: 'Datum', add: 'Hinzufügen', recentTransactions: 'Letzte Transaktionen', noTransactions: 'Noch keine Transaktionen.', income: 'Einkommen', expense: 'Ausgabe', pieChart: 'Kreisdiagramm', lineChart: 'Einnahmen/Ausgaben Analyse', currencyRates: 'Wechselkurse', currencyConverter: 'Währungsrechner', quantity: 'Menge', currency: 'Währung', target: 'Ziel', result: 'Ergebnis', exportPdf: 'Speichern (PDF)', exportCsv: 'Excel/CSV', preparing: 'Vorbereitung...', graphicSummary: 'Grafische Zusammenfassung', budgetReport: 'Budgetbericht', creationDate: 'Erstellungsdatum', period: 'Zeitraum', gold: 'Gramm Gold', silver: 'Gramm Silber', lastUpdate: 'Letzte Aktualisierung', monthlyLimit: 'Monatliches Budgetlimit' },
  es: { title: 'Rastreador de Presupuesto', subtitle: 'Administra tus finanzas fácilmente', netBalance: 'Saldo Neto', totalIncome: 'Ingresos Totales', totalExpense: 'Gastos Totales', budgetTarget: 'Objetivo de Presupuesto', used: 'Usado', addTransaction: 'Añadir Transacción', description: 'Descripción', amount: 'Cantidad', type: 'Tipo de Transacción', category: 'Categoría', date: 'Fecha', add: 'Añadir', recentTransactions: 'Transacciones Recientes', noTransactions: 'No hay transacciones.', income: 'Ingresos', expense: 'Gastos', pieChart: 'Gráfico Circular', lineChart: 'Análisis de Ingresos/Gastos', currencyRates: 'Tipos de Cambio', currencyConverter: 'Conversor de Moneda', quantity: 'Cantidad', currency: 'Moneda', target: 'Objetivo', result: 'Resultado', exportPdf: 'Guardar (PDF)', exportCsv: 'Excel/CSV', preparing: 'Preparando...', graphicSummary: 'Resumen Gráfico', budgetReport: 'Informe de Presupuesto', creationDate: 'Fecha de Creación', period: 'Período', gold: 'Gramo de Oro', silver: 'Gramo de Plata', lastUpdate: 'Última actualización', monthlyLimit: 'Límite de Presupuesto Mensual' },
  fr: { title: 'Suivi Budgétaire', subtitle: 'Gérez vos finances facilement', netBalance: 'Solde Net', totalIncome: 'Revenu Total', totalExpense: 'Dépenses Totales', budgetTarget: 'Objectif Budgétaire', used: 'Utilisé', addTransaction: 'Ajouter une Transaction', description: 'Description', amount: 'Montant', type: 'Type de Transaction', category: 'Catégorie', date: 'Date', add: 'Ajouter', recentTransactions: 'Transactions Récentes', noTransactions: 'Aucune transaction.', income: 'Revenu', expense: 'Dépense', pieChart: 'Diagramme Circulaire', lineChart: 'Analyse Revenus/Dépenses', currencyRates: 'Taux de Change', currencyConverter: 'Convertisseur de Devises', quantity: 'Quantité', currency: 'Devise', target: 'Cible', result: 'Résultat', exportPdf: 'Enregistrer (PDF)', exportCsv: 'Excel/CSV', preparing: 'Préparation...', graphicSummary: 'Résumé Graphique', budgetReport: 'Rapport Budgétaire', creationDate: 'Date de Création', period: 'Période', gold: 'Gramme d\'Or', silver: 'Gramme d\'Argent', lastUpdate: 'Dernière mise à jour', monthlyLimit: 'Limite Budgétaire Mensuelle' },
  ru: { title: 'Трекер Бюджета', subtitle: 'Управляйте финансами легко', netBalance: 'Чистый Баланс', totalIncome: 'Общий Доход', totalExpense: 'Общие Расходы', budgetTarget: 'Цель Бюджета', used: 'Использовано', addTransaction: 'Добавить Транзакцию', description: 'Описание', amount: 'Сумма', type: 'Тип Транзакции', category: 'Категория', date: 'Дата', add: 'Добавить', recentTransactions: 'Недавние Транзакции', noTransactions: 'Транзакций пока нет.', income: 'Доход', expense: 'Расход', pieChart: 'Круговая Диаграмма', lineChart: 'Анализ Доходов/Расходов', currencyRates: 'Курсы Валют', currencyConverter: 'Конвертер Валют', quantity: 'Количество', currency: 'Валюта', target: 'Цель', result: 'Результат', exportPdf: 'Сохранить (PDF)', exportCsv: 'Excel/CSV', preparing: 'Подготовка...', graphicSummary: 'Графическая Сводка', budgetReport: 'Бюджетный Отчет', creationDate: 'Дата Создания', period: 'Период', gold: 'Грамм Золота', silver: 'Грамм Серебра', lastUpdate: 'Последнее обновление', monthlyLimit: 'Ежемесячный Лимит Бюджета' },
  ja: { title: '家計簿', subtitle: '財務を簡単に管理', netBalance: '純残高', totalIncome: '総収入', totalExpense: '総支出', budgetTarget: '予算目標', used: '使用済み', addTransaction: '新しい取引を追加', description: '説明', amount: '金額', type: '取引タイプ', category: 'カテゴリー', date: '日付', add: '追加', recentTransactions: '最近の取引', noTransactions: '取引はまだありません。', income: '収入', expense: '支出', pieChart: '円グラフ', lineChart: '収入/支出分析', currencyRates: '為替レート', currencyConverter: '通貨コンバーター', quantity: '数量', currency: '通貨', target: '目標', result: '結果', exportPdf: '保存 (PDF)', exportCsv: 'Excel/CSV', preparing: '準備中...', graphicSummary: 'グラフィックサマリー', budgetReport: '予算レポート', creationDate: '作成日', period: '期間', gold: '金 (グラム)', silver: '銀 (グラム)', lastUpdate: '最終更新', monthlyLimit: '月間予算制限' }
};